### PR TITLE
convert from .net 4.5 to 4.0

### PR DESCRIPTION
**Pull request by arielflashner**
This minor change allows the project to run on machines not having .net 4.5 installed

### CODE REVIEW

**Review by bubibubi — COMMENTED** [review]
Hi, what did you solve returning OleDbType.DBTime? I think that TimeSpan still don't work because of the wrong returned type from the JetDataReader

**Comment by bubibubi** [comment]
I released Model63_Time test and some fixes related to this error. TimeSpan still does not work during read. Any ideas?

**Comment by bubibubi** [comment]
Ok, I fixed it using a behaviour of EF (it never calls DataReader.GetValue with DateTime so I can assume that it is a TimeSpan).

**Comment by arielflashner** [comment]
My first change fixed saving TimeSpan properties.
I was indeed in the middle of a complete read+write fix - thanks for sharing our complete fix !

**Pull request closed without merging**
